### ISSUE TITLE
Template loading doesn't work on windows

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-cg#11]
Template loading works like this:

1. We create a [jinja2 environment](https://jinja.palletsprojects.com/en/2.10.x/api/#jinja2.Environment) which contains a [loader](https://jinja.palletsprojects.com/en/2.10.x/api/#loaders) to load templates. It is instantiated with a path relative to our package name where all templates are stored, i.e. `templates`
2. We select a template in some subdir of templates, e.g. to get `[our package]/templates/weblab/template.txt` we would do `os.path.join('weblab', 'template.txt')`
3. We pass the output of os.path.join to `env.get_template`

Works on linux, not on windows

**Comment by MichaelClerx** [comment]
Why? Seems that the jinja people want everything to be specified as posix paths, rather than using local conventions... 
See e.g. https://github.com/pallets/jinja/issues/767#issuecomment-327848886

**Comment by ThiefMaster** [comment]
Use `posixpath.join()` for template paths.
