### ISSUE TITLE
Now that cellmlmanip has updated sympy I'm getting an error. Do we even really need this in the requirement list as cellmlmanip wouuld require it?

### ISSUE THREAD

**Issue by MauriceHendrix** [ModellingWebLab/weblab-cg#22]
ERROR: cellmlmanip 0.0.1 has requirement sympy>=1.4, but you'll have sympy 1.1.1 which is incompatible.

**Comment by MichaelClerx** [comment]
Yeah it's only the pinning thing that causes this. Not mentioned as a direct dependency at all. Will fix
