### ISSUE TITLE
Weblab_cg is generating Cython. I'm wondering what the advantages are and whether I would be better off generating C++ directly for chaste.

### ISSUE THREAD

**Issue by MauriceHendrix** [ModellingWebLab/weblab-cg#26]
The weblab_cg is generating Cython. I'm wondering what the advantages are and whether I would be better off generating C++ directly for chaste. 
The generation for chaste should eventually replace PyCML and generate .cpp and .hpp files. I anticipate tests will test generated .cpp and .hpp against reference files made with PyCML. It would be no doubt possible to generate an intermediate Cython but it seems easier to just directly generate .cpp and .hpp files.

**Comment by mirams** [comment]
Yeah, I think that's the idea

**Comment by jonc125** [comment]
Yeah, for Chaste definitely generate C++ directly. The Cython output is just for Web Lab.
