### ISSUE TITLE
'Abs' function unsupported

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/weblab-cg#33]
Generating code for a model that uses 'Abs' tells me that it is not supported.
src/weblab-cg/weblab_cg/_printer.py:203: in _print_Function
   raise ValueError('Unsupported function: ' + str(name))
E   ValueError: Unsupported function: Abs

earm_noble_model_1990.cellml

**Comment by MauriceHendrix** [comment]
@MichaelClerx I'm proposing a fix #42
