### ISSUE TITLE
derivative declarations currently after st use (leading to c++ compile error)

### ISSUE THREAD

**Issue by MauriceHendrix** [ModellingWebLab/weblab-cg#47]
**Problem:**
For some models equations have derivatives in them. This leads to the following situation (leading to compile error as the variable is used before it is declared.
```
const double var_cell__J_CaB_junction = d_dt_chaste_interface__cell__sSLHj + d_dt_chaste_interface__cell__sSLLj; // dimensionless
const double d_dt_chaste_interface__cell__sSLHj = -var_cell__koff_slh * var_chaste_interface__cell__sSLHj + (-var_chaste_interface__cell__sSLHj + var_cell__Bmax_SLhighj) * var_cell__kon_slh * var_chaste_interface__cell__sCaj; // 1 / millisecond
...
const double d_dt_chaste_interface__cell__sCaj = -var_cell__J_CaB_junction + (-var_chaste_interface__cell__sCaj + var_chaste_interface__cell__sCasl) * var_cell__J_ca_juncsl / var_cell__Vjunc + var_cell__J_SRCarel * var_cell__Vsr / var_cell__Vjunc + var_cell__J_SRleak * var_cell__Vmyo / var_cell__Vjunc - 0.5 * var_cell__Cmem * var_cell__I_Ca_tot_junc / (var_cell__Frdy * var_cell__Vjunc); // 1 / millisecond
```

**Proposed solution:**
- Make final derivative declarations indirect via a linker variable:
```
const double var_d_dt_chaste_interface__cell__sCaj = -var_cell__J_CaB_junction + (-var_chaste_interface__cell__sCaj + var_chaste_interface__cell__sCasl) * var_cell__J_ca_juncsl / var_cell__Vjunc + var_cell__J_SRCarel * var_cell__Vsr / var_cell__Vjunc + var_cell__J_SRleak * var_cell__Vmyo / var_cell__Vjunc - 0.5 * var_cell__Cmem * var_cell__I_Ca_tot_junc / (var_cell__Frdy * var_cell__Vjunc); // 1 / millisecond
const double d_dt_chaste_interface__cell__sCaj = var_d_dt_chaste_interface__cell__sCaj
```
- create the `linker_location` in ordered dict of `{deriv:eq}` with `eq` initially None
- Go backwards through the equations:
-- Check if moving is necessary by looking at symbols_and_derivs and seeing if they match our derivs. Update `linker_location`.
-- Finally we can now generate the full eq list. We'll go backwards through the the `linker_location` and insert the linker before the eq it needs to be before. This will preserve the order if any eqs have more derivatives in them.

**Comment by jonc125** [comment]
Hmm. Looking at the `graph` method it supports having derivative nodes on both LHS and RHS - assuming `find_symbols_and_derivatives` returns derivatives like it claims, an edge should be added in the graph so that the equation with say dy/dt on the RHS depends on the equation defining dy/dt. Is this the case in the model you're testing?

If it is, what happens to the output of `get_equations_for` in this case? Based on the test added in #167, it appears to put equations in the correct order.

So, providing you give dy/dt the same name whether it appears on the LHS or RHS, I'm not sure how this issue arises?

**Comment by MauriceHendrix** [comment]
Aaah!
Thanks for mentioning that. I just looked again and I'm sorting the resulting equations to get the derivative definitions at the end that's how it happend. 2 possibl solutions:
- Just remove sort and accept final derivative declarations aren't all at the end
- Replace all derivatives by var_<deriv_name> and declare <deriv_name> = var_deriv_name at the end
@mirams what do you think?

**Comment by jonc125** [comment]
pycml doesn't put final derivative declarations at the end. The only bit that comes at the end is filling in the ydot vector for the ODE solver - which reads all the derivative variables in order.

**Comment by MauriceHendrix** [comment]
> pycml doesn't put final derivative declarations at the end. The only bit that comes at the end is filling in the ydot vector for the ODE solver - which reads all the derivative variables in order.

For all models I've seen so far all of the following type of declarations are at the end of the blacok of equations in `EvaluateYDerivatives`
`const double d_dt_chaste_interface__cell__sm = var_chaste_interface__cell__d_sm_d_cell__time;`
I haven't seen any such declarations in the middle.

**Comment by jonc125** [comment]
Hmm! Well, I certainly don't remember adding anything explicit to do that :grin: It might be caused as a side effect of connections between components and the ODE splitting logic when conversions are required?

**Comment by MauriceHendrix** [comment]
> Hmm! Well, I certainly don't remember adding anything explicit to do that  It might be caused as a side effect of connections between components and the ODE splitting logic when conversions are required?

Aah yeah could be. So maybe just output as they come rather than adding lots of code to be only somewhat similar to pycml (were not getting any of the linking cars and eqs and terms within them in different but still correct order so it already looks quite different)

**Comment by MauriceHendrix** [comment]
I just make a pull request with the removed sort #48
